#!/bin/bash
# Get the Python file name from the environment variable
PYFILE="$PYFILE"

# Compile the Python script using py_compile
python3 - << END
import py_compile
py_compile.compile('$PYFILE', '$PYFILE' + 'c')
print("Compiling $PYFILE ...")
END
